server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          force-pull: true
          uri: https://github.com/microservices-1/config-repo-new.git
          username:
          password: "{cipher}18d4d4812cef498f269ea1f513f4f1c29ae59536c237de14c408f855c5d2d269"
          search-paths: userservice, itemservice
        encrypt:
          enabled: false




